In [4]:
import numpy as np
patterns = np.array([
    [1, 1, -1,  -1],
    [1,  -1, 1,  -1],
    [-1,  1,  1, -1],
    [-1, -1,  1, 1]])
W = np.dot(patterns.T, patterns)

np.fill_diagonal(W, 0)

print("Weight Matrix:\n", W)

test_patterns = np.array([
    [1,  1, -1,  1],
    [-1, -1, -1, 1],
    [1,  1,  1, -1],
])

def sign(x):
    return np.where(x >= 0, 1, -1)

output = sign(np.dot(test_patterns, W))

print("\nOutput Patterns:\n", output)

Weight Matrix:
 [[ 0  0 -2 -2]
 [ 0  0 -2 -2]
 [-2 -2  0  0]
 [-2 -2  0  0]]

Output Patterns:
 [[ 1  1 -1 -1]
 [ 1  1  1  1]
 [ 1  1 -1 -1]]
