In [1]:
import numpy as np

In [2]:
x = np.array([
    [1, 1, 1],
    [-1, -1, 1]
])

y = np.array([
    [1, 1, -1, -1],
    [-1, -1, 1, 1]
])

In [3]:
W = np.dot(x.T, y)
print("W:\n", W)

W:
 [[ 2  2 -2 -2]
 [ 2  2 -2 -2]
 [ 0  0  0  0]]


In [7]:
def sign(x):
    return np.where(x >= 0, 1, -1)

In [5]:
y1_out = sign(np.dot(x[0], W))
y2_out = sign(np.dot(x[1], W))

print("\nForward Output:")
print("y1:", y1_out)
print("y2:", y2_out)


Forward Output:
y1: [ 1  1 -1 -1]
y2: [-1 -1  1  1]


In [6]:
x1_out = sign(np.dot(y1_out, W.T))
x2_out = sign(np.dot(y2_out, W.T))

print("\nBackward Output:")
print("x1:", x1_out)
print("x2:", x2_out)


Backward Output:
x1: [1 1 1]
x2: [-1 -1  1]
